AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  shipping-tracker

  Sample SAM Template for shipping-tracker

Globals:
  Function:
    Timeout: 20

Resources:
  ShippingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ShippingFunction
      Handler: tl.develoveper.lambda.shipping.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          DB_URL: jdbc:postgresql://shipping/postgres
          DB_USER: postgres
          DB_PASSWORD: shipping
      Events:
        CreateConsignment:
          Type: Api
          Properties:
            Path: /consignment
            Method: post
        ViewConsignment:
          Type: Api
          Properties:
            Path: /consignment/{id}
            Method: get
        AddConsignmentItem:
          Type: Api
          Properties:
            Path: /consignment/{id}/item
            Method: post
        CheckInConsignment:
          Type: Api
          Properties:
            Path: /consignment/{id}/check-in
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ShippingFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ShippingFunction.Arn
  ShippingFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ShippingFunctionRole.Arn
    
